###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'master'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Get Python Setup
        uses: actions/setup-python@v1
        
      - name: Get dependencies
        run: |
          sudo apt-get install libgeos-dev
          pip install pylint setuptools
          pip install -r requirements.txt 

      - name: Run Linter
        run: |
          cd $GITHUB_WORKSPACE
          pylint --rcfile=.pylintrc srunner/
          pylint --rcfile=.pylintrc scenario_runner.py
            